### ISSUE TITLE
Api extractor will strip `declare var` content after bundling types

### ISSUE THREAD

**Issue by ghiscoding** [qmhc/unplugin-dts#416]
### Describe the bug

Hello, I seem to get a regression bug with the new v4.5.1 in my project, I'm getting this error but only with the new version. If I try again the old version, by fixing the version to `4.5.0` in my package.json, then it works again without errors. 

```sh
[vite:dts] Internal Error: Unable to follow symbol for "__VLS_PrettifyGlobal"
```

### Reproduction

https://github.com/ghiscoding/slickgrid-universal/actions/runs/13590117309/job/37997418809

### Steps to reproduce

```sh
git clone https://github.com/ghiscoding/slickgrid-universal
pnpm install
pnpm run bundle
pnpm run vue:build:framework
```

**Note** after cloning the repo, you have to modify the [`frameworks/slickgrid-vue/package.json`](https://github.com/ghiscoding/slickgrid-universal/blob/master/frameworks/slickgrid-vue/package.json#L84) to use latest version of `vite-plugin-dts` which is not currently the latest since it caused a regression

The project is a monorepo, which might be a little too large but I hope that you can find the issue without requiring another project repro. Again it's really caused by the latest version only, 4.5.0 is ok but 4.5.1 is breaking

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.93 GB / 15.85 GB
  Binaries:
    Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.15.5 - C:\GitHub\slickgrid-universal\node_modules\.bin\pnpm.CMD
  Browsers:
    Edge: Chromium (131.0.2903.112)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vitejs/plugin-vue: ^5.2.1 => 5.2.1 
    vite: catalog: => 6.0.11 
    vite-plugin-dts: ^4.5.1 => 4.5.1
```

### Validations

- [x] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [x] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by silverwind** [comment]
> v3.5.1

You meant v4.5.1?

**Comment by ghiscoding** [comment]
> > v3.5.1
> 
> You meant v4.5.1?

oops... yes sorry, I inversed the number 😆

**Comment by skirtles-code** [comment]
I'm seeing the same problem with 4.5.1. I tried to create a minimal-ish reproduction:

<https://github.com/skirtles-code/vite-plugin-dts-416-repro>

It's based on the default project created using `npm create vue@latest`.

The main factors seem to be:

1. `rollupTypes: true`.
2. A component using `<slot />`.

**Comment by brc-dd** [comment]
locking volar to older version seems to work: might be an upstream regression

```json
  "overrides": {
    "@vue/language-core": "2.2.0"
  }
```

**Comment by brc-dd** [comment]
bisecting shows this is the commit that broke - https://github.com/vuejs/language-tools/commit/c4c0413ecac9bc9223783be32c64a9edbab8eefa

**Comment by qmhc** [comment]
@brc-dd Thanks for your research. I will degrade the version of `@vue/language-core` and release a new patch version.

**Comment by brc-dd** [comment]
It seems that the volar's global types block is missing in generated dist/App.vue.d.ts. If we can inject it there somehow it will work. Output without bundling should be similar to when you run `pnpm vue-tsc --emitDeclarationOnly --declaration src/App.vue`.

mkdist also is broken since newer releases. Also, this wasn't throwing without rollupTypes, but still the emitted types were broken.

**Comment by brc-dd** [comment]
https://github.com/vuejs/language-tools/pull/5239 seems to fix the upstream issue and the intermediate files have correct types now. But the api extractor output is still wrong:

emitted code (by volar):

```ts
declare var __VLS_1: {};
type __VLS_Slots = {} & {
    default?: (props: typeof __VLS_1) => any;
};
declare const __VLS_component: import('vue').DefineComponent<{}, {}, {}, {}, {}, import('vue').ComponentOptionsMixin, import('vue').ComponentOptionsMixin, {}, string, import('vue').PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import('vue').ComponentProvideOptions, true, {}, any>;
declare const _default: __VLS_WithSlots<typeof __VLS_component, __VLS_Slots>;
export default _default;
type __VLS_WithSlots<T, S> = T & {
    new (): {
        $slots: S;
    };
};
```

bundled code:

```ts
import { ComponentOptionsMixin } from 'vue';
import { ComponentProvideOptions } from 'vue';
import { DefineComponent } from 'vue';
import { PublicProps } from 'vue';

declare const __VLS_component: DefineComponent<    {}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, ComponentProvideOptions, true, {}, any>;

declare type __VLS_Slots = {} & {
    default?: (props: typeof __VLS_1) => any;
};

declare type __VLS_WithSlots<T, S> = T & {
    new (): {
        $slots: S;
    };
};

export declare const App: __VLS_WithSlots<typeof __VLS_component, __VLS_Slots>;

export { }
```

Notice `__VLS_1` declaration is stripped.

**Comment by qmhc** [comment]
With latest `@vue/language-core` the issue which occurred from the plugin is fixed.

To follow the original issue from Api extractor, please refer to https://github.com/microsoft/rushstack/issues/5146.

**Comment by kleinfreund** [comment]
I'm still seeing this issue using `dts({ bundleTypes: true, processor: 'vue' })` with

- `unplugin-dts@1.0.0-beta.6` (or `vite-plugin-dts@5.0.0-beta.6`)
- `@vue/language-core@3.0.5`
- `@microsoft/api-extractor@7.52.10`

which are the respective latest versions of the relevant tools.

Switching from `vite-plugin-dts@4.5.4` to `unplugin-dts@1.0.0-beta.6`, I get (rest stripped for brevity):

```ts
declare type __VLS_Slots = {} & {
    'hue-range-input-label'?: (props: typeof __VLS_1) => any;
} & {
    'alpha-range-input-label'?: (props: typeof __VLS_3) => any;
} & {
    'copy-button'?: (props: typeof __VLS_5) => any;
} & {
    actions?: (props: typeof __VLS_7) => any;
} & {
    'format-switch-button'?: (props: typeof __VLS_9) => any;
};
```

As before, the `__VLS_1` variables are erased from the bundled output. This should reproduce readily on https://github.com/kleinfreund/vue-accessible-color-picker making the relevant changes and running `npm install && npm run build`.
